class DacQueries {
    static QUERY_GET_USER = `SELECT USER_ID, PASSWORD FROM DacUser`;
    static QUERY_COUNT_SESSIONS = `SELECT COUNT(*) FROM UserSessionInfo WHERE USER_ID = ?`;
    static QUERY_GET_PROPS_DAC_CONFIGURATION = `SELECT PROPNAME, PROPVAL FROM DacConfiguration WHERE PROPNAME IN (?)`;
    static QUERY_GET_ALL_KEYS_DAC_CONFIGURATION =`SELECT PROPNAME, PROPVAL FROM DacConfiguration WHERE PROPNAME LIKE '%key%'`;
    static QUERY_UPDATE_DAC_CONFIG_VALUE =`UPDATE DacConfiguration SET PROPVAL = ? WHERE PROPNAME = ?`;
    static QUERY_INSERT_SESSION = `INSERT INTO UserSessionInfo (USER_ID, DIGEST, LOGIN_TIME, LAST_ACCESS_TIME, MACHINE_IP, OS, BROWSER, DEVICE_TYPE) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`;
    static QUERY_REMOVE_STALE_SESSIONS = "DELETE FROM UserSessionInfo WHERE USER_ID = ? AND MACHINE_IP = ? AND OS = ? AND BROWSER = ?;";
    static QUERY_DELETE_SESSIONS_BY_DIGEST = "DELETE FROM UserSessionInfo WHERE DIGEST = ?;";
    static QUERY_DELETE_EXPIRED_SESSIONS = "DELETE FROM UserSessionInfo WHERE LAST_ACCESS_TIME < (UNIX_TIMESTAMP() -?);";
    static QUERY_CHECK_DIGEST = "SELECT 1 FROM UserSessionInfo WHERE DIGEST = ?";
    static QUERY_UPDATE_LAST_ACCESSED = "UPDATE UserSessionInfo SET LAST_ACCESS_TIME = ? WHERE DIGEST = ?";
}   

export default DacQueries;
